### ISSUE TITLE
blogs/JAVASCRIPT/Javascript-event.md的另一观点

### ISSUE THREAD

**Issue by langgo** [zhukejin1223/blogs#1]
```
window (1) -> document (1) -> body (1) -> ul (1) -> li -> ul (2) -> body (2) -> document (2) -> window (2)
```

> 在浏览器支持addEventListener的前提下
> addEventListener(ul, function(){}, true)
> // 这里的ul, 是 ul(1)
> addEventListener(ul, function(){}, false)
> // 这里的ul, 是 ul(2)
> 
> 我的看法，这样理解才更加正确

**Comment by zhukejin** [comment]
#3 正解
