### ISSUE TITLE
事件流

### ISSUE THREAD

**Issue by fh408931** [zhukejin1223/blogs#3]
事件传播三阶段：
1.capture phase （事件捕获）
2.target phase （处于目标）
3.bubbling phase （事件冒泡）
在 target phase，event handler 被调用的顺序不再遵循先捕获，后冒泡的原则，而是严格按照 event handler 注册的顺序，先注册，故而先执行。要改变二者的执行顺序，只需要改变两段源码的顺序即可。
W3C 规范：
Next, the implementation must determine the current target's candidate event listeners. This must be the list of all event listeners that have been registered on the current target in their order of registration. [HTML5] defines the ordering of listeners registered through event handler attributes. Once determined, the candidate event listeners must not be changed. Adding or removing listeners does not affect the current target's candidate event listeners.
https://stackoverflow.com/questions/18103391/usecapture-in-addeventlistener-behaves-strangely?lq=1
https://stackoverflow.com/questions/11841330/event-listeners-registered-for-capturing-phase-not-triggered-before-bubbling-w

**Comment by zhukejin** [comment]
学习了
